import item2 from "../../assets/images/test-itme2.png";

export const dummyProducts = [
  {
    id: "1",
    name: "룬 블레이드",
    price: 1200,
    image: item2,
    description: "마법이 깃든 전설의 검",
  },
  {
    id: "2",
    name: "엘프의 활",
    price: 900,
    image: item2,
    description: "정확도가 뛰어난 활",
  },
  {
    id: "3",
    name: "화염 지팡이",
    price: 1500,
    image: item2,
    description: "불 속성의 마법 지팡이",
  },
  {
    id: "4",
    name: "얼음 단검",
    price: 800,
    image: item2,
    description: "냉기를 담은 단검",
  },
  {
    id: "5",
    name: "고블린 해머",
    price: 1000,
    image: item2,
    description: "무거운 전투용 해머",
  },
  {
    id: "6",
    name: "빛의 방패",
    price: 1100,
    image: item2,
    description: "성스러운 보호막",
  },
  {
    id: "7",
    name: "그림자 활",
    price: 950,
    image: item2,
    description: "어둠 속에서 효과적",
  },
  {
    id: "8",
    name: "대지의 도끼",
    price: 1300,
    image: item2,
    description: "강력한 도끼",
  },
  {
    id: "9",
    name: "바람 검",
    price: 1050,
    image: item2,
    description: "민첩한 바람의 검",
  },
  {
    id: "10",
    name: "마법서",
    price: 1400,
    image: item2,
    description: "고대 주문이 적힌 책",
  },
  {
    id: "11",
    name: "독 침지팡이",
    price: 1250,
    image: item2,
    description: "중독 효과",
  },
  {
    id: "12",
    name: "불사의 투구",
    price: 1600,
    image: item2,
    description: "불사의 힘을 부여",
  },
];
