// import item2 from "../../assets/images/test-itme2.png";

// export const dummyProducts = [
//   {
//     itemPk: 15,
//     itemName: "마스터 소드",
//     itemPrice: 2000,
//     itemCategory: "검",
//     itemImageUrl: item2,
//     itemDescription:
//       "젤다의 전설의 성검이자 봉인의 검. 어둠의 군주 가논을 봉인하기 위해 선택된 '용사'에게만 빛을 발합니다. 검날은 빛을 발하며, 악을 베어내는 힘을 지녔지만, 그 힘은 순수한 용기와 희생이 있을 때에만 완벽해집니다.",
//     itemEffect: "공격 180",
//     itemInventory: 2,
//     createdAt: "2025-06-12T12:00:00.000000",
//   },
//   {
//     itemPk: 14,
//     itemName: "우레폭풍, 바람추적자의 축복받은 검",
//     itemPrice: 1900,
//     itemCategory: "검",
//     itemImageUrl: item2,
//     itemDescription:
//       "WoW 전설의 무기. 번개의 정수를 봉인한 무기로, 천둥의 시대에 제왕이 사용했다 전해집니다. 공격할 때마다 전격이 튀며, 주변이 번개에 휩싸이는 효과를 발휘합니다.",
//     itemEffect: "공격 175",
//     itemInventory: 1,
//     createdAt: "2025-06-12T12:00:00.000000",
//   },
//   {
//     itemPk: 13,
//     itemName: "집행자의 검",
//     itemPrice: 1850,
//     itemCategory: "검",
//     itemImageUrl: item2,
//     itemDescription:
//       "리니지에서 ‘집행검’이라 불리며, 켄라우헬의 피로 단련된 전설의 칼날. 피를 베면 어두운 오오라가 퍼지고, 적의 체력을 흡수해 전투 지속력을 높입니다.",
//     itemEffect: "공격 170",
//     itemInventory: 1,
//     createdAt: "2025-06-12T12:00:00.000000",
//   },
//   {
//     itemPk: 12,
//     itemName: "윈드포스",
//     itemPrice: 1800,
//     itemCategory: "활",
//     itemImageUrl: item2,
//     itemDescription:
//       "디아블로 II의 전설적 활. 바람의 힘이 깃들어, 낮은 탄속에도 치명적인 타격을 가합니다. 화살이 날아갈 때마다 바람의 잔향이 남아 적을 흔들며, 진정한 아마존의 전설로 기억됩니다.",
//     itemEffect: "공격 160",
//     itemInventory: 2,
//     createdAt: "2025-06-12T12:00:00.000000",
//   },
//   {
//     itemPk: 11,
//     itemName: "지옥불 횃불",
//     itemPrice: 1750,
//     itemCategory: "지팡이",
//     itemImageUrl: item2,
//     itemDescription:
//       "디아블로 II에서 악마의 심장을 봉인한 횃불. 영혼을 불태우는 불길이 끊임없이 타오르며, 사용자의 영혼도 조금씩 갉아먹습니다.",
//     itemEffect: "공격 155",
//     itemInventory: 1,
//     createdAt: "2025-06-12T12:00:00.000000",
//   },
//   {
//     itemPk: 10,
//     itemName: "아즈모단의 잔혹한 지팡이",
//     itemPrice: 1700,
//     itemCategory: "지팡이",
//     itemImageUrl: item2,
//     itemDescription:
//       "디아블로 III 유저들 사이에서 불타는 지옥불의 상징으로 불리는 마력의 지팡이. 악마의 의지가 깃들어 있으며, 사악한 화염 마법을 증폭시킵니다.",
//     itemEffect: "공격 150",
//     itemInventory: 2,
//     createdAt: "2025-06-12T12:00:00.000000",
//   },
//   {
//     itemPk: 9,
//     itemName: "망각의 지팡이",
//     itemPrice: 1650,
//     itemCategory: "지팡이",
//     itemImageUrl: item2,
//     itemDescription:
//       "엘더스크롤 시리즈의 금단된 마법 도구. 언데드의 저주를 담고 있으며, 맞은 자는 기억을 잃고 존재마저 희미해집니다.",
//     itemEffect: "공격 148",
//     itemInventory: 3,
//     createdAt: "2025-06-12T12:00:00.000000",
//   },
//   {
//     itemPk: 8,
//     itemName: "이글혼 활",
//     itemPrice: 1600,
//     itemCategory: "활",
//     itemImageUrl: item2,
//     itemDescription:
//       "하스스톤과 워크래프트 세계에서 명성을 얻은 전설의 활. 독수리 깃털로 만들어졌으며, 날카로운 정확도와 위협적인 외형을 자랑합니다.",
//     itemEffect: "공격 145",
//     itemInventory: 3,
//     createdAt: "2025-06-12T12:00:00.000000",
//   },
//   {
//     itemPk: 7,
//     itemName: "빛의 복수",
//     itemPrice: 1550,
//     itemCategory: "검",
//     itemImageUrl: item2,
//     itemDescription:
//       "울두아르에서 타락한 빛의 무기. 성스러운 힘과 분노가 공존하며, 타락한 자를 단죄하기 위해 창조된 검입니다.",
//     itemEffect: "공격 142",
//     itemInventory: 1,
//     createdAt: "2025-06-12T12:00:00.000000",
//   },
//   {
//     itemPk: 6,
//     itemName: "죽음의 인도자 활",
//     itemPrice: 1500,
//     itemCategory: "활",
//     itemImageUrl: item2,
//     itemDescription:
//       "WoW 언데드 헌터의 전용 무기. 어둠과 저주의 힘을 깃들인 활로, 생명을 겨냥해 날리는 화살은 절대 비껴가지 않습니다.",
//     itemEffect: "공격 140",
//     itemInventory: 2,
//     createdAt: "2025-06-12T12:00:00.000000",
//   },
//   {
//     itemPk: 5,
//     itemName: "타오르는 방패",
//     itemPrice: 1450,
//     itemCategory: "방패",
//     itemImageUrl: item2,
//     itemDescription:
//       "디아블로 III에서 등장하는 불꽃의 방패. 용암처럼 끓는 표면이 적의 무기를 튕겨내며, 불덩이를 튀깁니다.",
//     itemEffect: "공격 120",
//     itemInventory: 4,
//     createdAt: "2025-06-12T12:00:00.000000",
//   },
//   {
//     itemPk: 4,
//     itemName: "명예의 아이기스",
//     itemPrice: 1400,
//     itemCategory: "방패",
//     itemImageUrl: item2,
//     itemDescription:
//       "MMORPG 세계에서 기사단의 상징. 순은과 금으로 세공된 신성한 방패로, 전장에서 왕국의 방패라 불렸습니다.",
//     itemEffect: "공격 118",
//     itemInventory: 3,
//     createdAt: "2025-06-12T12:00:00.000000",
//   },
//   {
//     itemPk: 3,
//     itemName: "용화의 방벽",
//     itemPrice: 1350,
//     itemCategory: "방패",
//     itemImageUrl: item2,
//     itemDescription:
//       "용의 숨결로 단련된 전설의 방패. 불꽃과 용암을 견디는 힘이 있으며, 드래곤 라이더들이 전투에서 생존할 수 있었던 비밀입니다.",
//     itemEffect: "공격 122",
//     itemInventory: 2,
//     createdAt: "2025-06-12T12:00:00.000000",
//   },
//   {
//     itemPk: 2,
//     itemName: "워의 지팡이",
//     itemPrice: 1300,
//     itemCategory: "지팡이",
//     itemImageUrl: item2,
//     itemDescription:
//       "디아블로 III에서 등장하는 전설 지팡이. 번개와 냉기의 조화를 이루며, 마법 시전 시 폭발적인 힘을 발휘합니다.",
//     itemEffect: "공격 138",
//     itemInventory: 3,
//     createdAt: "2025-06-12T12:00:00.000000",
//   },
//   {
//     itemPk: 1,
//     itemName: "수호자의 위대한 지팡이, 아티에시",
//     itemPrice: 1250,
//     itemCategory: "지팡이",
//     itemImageUrl: item2,
//     itemDescription:
//       "WoW에서 키린 토 수호자에게 전해진 고대 유물. 세계수의 가지가 박혀 있으며, 마법사와 사제들에게 가장 신성한 성물로 전해졌습니다.",
//     itemEffect: "공격 135",
//     itemInventory: 2,
//     createdAt: "2025-06-12T12:00:00.000000",
//   },
// ];
